INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6008, 'pierrex2', '훌륭한 숙박이었습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6009, 'user05', '매우 편안하고 깨끗했습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7000, 'user01', '좋은 위치지만 조금 시끄러웠습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7001, 'user02', '가격에 비해 별로였습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7002, 'user03', '서비스가 환상적이었고 직원들이 친절했습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7003, 'user04', '괜찮았지만 더 나아질 수 있습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7004, 'user05', '멋진 시간을 보냈습니다!', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7005, 'user06', '직원들이 매우 도움을 주었습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7006, 'user07', '조식 옵션이 좋았습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7007, 'user08', '다시 방문할 것입니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7008, 'user09', '그저 그렇습니다, 특별한 건 없었습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7009, 'user10', '가격에 비해 너무 비쌉니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7010, 'user11', '아주 아늑한 분위기였습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7011, 'user12', '객실에서 멋진 전망이 있었습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7012, 'user13', '청결하지만 방이 작았습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1004, 'user14', '직원 교육이 더 필요합니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7013, 'user15', '주말 getaway에 완벽했습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7014, 'user16', '조금 오래된 느낌이지만 여전히 좋았습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7015, 'user17', '가격에 비해 더 많은 기대를 했습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7016, 'user18', '우수한 시설이었습니다!', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7017, 'user19', '정말 즐거운 숙박이었습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7018, 'user20', '좋은 위치지만 밤에는 시끄럽습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7019, 'user21', '전반적으로 기분 좋은 경험이었습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7020, 'user22', '시내 중심에서 너무 멀었습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7021, 'user23', '수영장 지역이 좋았습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7022, 'user24', '에어컨 문제로 어려움이 있었습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7023, 'user25', '훌륭한 편의시설이었습니다!', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7024, 'user26', '다시 머무르지 않을 것입니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7025, 'user27', '훌륭한 식사 옵션이 있었습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7026, 'user28', '친절한 직원들이었습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7027, 'user29', '보통의 경험이었습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7028, 'user30', '체크인 과정이 불편했습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7029, 'user31', '이 호텔을 강력히 추천합니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7030, 'user32', '매우 깨끗하고 좋았습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7031, 'user33', '가족에게 좋습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7032, 'user34', '반드시 돌아올 것입니다!', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7033, 'user35', '환상적인 경험이었습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7034, 'user36', '직원이 도움이 되지 않았습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7035, 'user37', '그다지 인상적이지 않았습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7036, 'user38', '스파 서비스가 좋았습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7037, 'user39', '가격 대비 훌륭한 가치입니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7038, 'user40', '보통의 숙박이었습니다.', 4);

