INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'pierrex2', 'Great experience!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1006, 'user05', 'Very comfortable stay.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1007, 'user01', 'Average service.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1008, 'user02', 'Excellent location.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1009, 'user03', 'Not worth the price.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1010, 'user04', 'Would come back again.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1011, 'user05', 'Clean and tidy.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1012, 'user06', 'Very helpful staff.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1014, 'user07', 'Room was a bit small.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1015, 'user08', 'Lovely ambiance.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1018, 'user09', 'Too noisy at night.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1016, 'user10', 'Great breakfast options.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1017, 'user11', 'Will definitely return!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2001, 'user12', 'Nice view from the room.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2002, 'user13', 'Service could be improved.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2003, 'user14', 'A pleasant experience.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2004, 'user15', 'Not as expected.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2005, 'user16', 'Great facilities!', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2006, 'user17', 'Friendly staff.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2007, 'user18', 'Could use some renovations.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2008, 'user19', 'Good value for money.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3001, 'user20', 'Would recommend to others.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3002, 'user21', 'Average stay.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3003, 'user22', 'Excellent customer service.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3004, 'user23', 'Not very clean.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3005, 'user24', 'Fantastic experience overall.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3006, 'user25', 'Enjoyed my stay.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3007, 'user26', 'Will not return.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3008, 'user27', 'Satisfactory experience.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4001, 'user28', 'Loved the location!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4002, 'user29', 'Decent hotel.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4003, 'user30', 'Not my favorite.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4004, 'user31', 'Great staff!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4005, 'user32', 'Okay for a short stay.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4006, 'user33', 'Had a pleasant time.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4007, 'user34', 'Not impressed.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4008, 'user35', 'Exceptional service.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1005, 'user36', 'Will not stay again.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5005, 'user37', 'Loved the amenities.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5006, 'user38', 'Very noisy.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5007, 'user39', 'Good for families.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5008, 'user40', 'Had a great time.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5009, 'user41', 'Not recommended.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5010, 'user42', 'Fantastic experience!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5011, 'user43', 'Very clean.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5012, 'user01', 'Just okay.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5013, 'user02', 'Average stay.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6000, 'user03', 'Loved the pool!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6001, 'user04', 'Will be back!', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6002, 'user05', 'Okay experience.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6003, 'user06', 'Not as good as expected.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6004, 'user07', 'Great location!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6005, 'user08', 'Very friendly staff.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6006, 'user09', 'Not bad.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6007, 'user10', 'Could be better.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6008, 'user11', 'Great value for money.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6009, 'user12', 'Satisfactory stay.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6010, 'user13', 'Will return.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6006, 'user14', 'Had a terrible experience.', 1);
