INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6008, 'pierrex2', '', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6009, 'user05', '', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7000, 'user01', '', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7001, 'user02', '', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7002, 'user03', '', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7003, 'user04', '', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7004, 'user05', '', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7005, 'user06', '', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7006, 'user07', '', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7007, 'user08', '', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7008, 'user09', '', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7009, 'user10', '', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7010, 'user11', '', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7011, 'user12', '', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7012, 'user13', '', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1004, 'user14', '', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7013, 'user15', '', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7014, 'user16', '', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7015, 'user17', '', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7016, 'user18', '', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7017, 'user19', '', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7018, 'user20', '', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7019, 'user21', '', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7020, 'user22', '', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7021, 'user23', '', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7022, 'user24', '', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7023, 'user25', '', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7024, 'user26', '', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7025, 'user27', '', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7026, 'user28', '', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7027, 'user29', '', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7028, 'user30', '', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7029, 'user31', '', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7030, 'user32', '', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7031, 'user33', '', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7032, 'user34', '', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7033, 'user35', '', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7034, 'user36', '', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7035, 'user37', '', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7036, 'user38', '', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7037, 'user39', '', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 7038, 'user40', '', 4);
-- 호텔 ID: 1013
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'pierrex2', '아주 만족스러운 경험이었습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user05', '서비스가 훌륭했어요.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user01', '방이 깨끗하고 편안했습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user02', '조식이 맛있었어요.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user03', '가격 대비 만족스러웠습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user04', '위치가 좋았어요.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user05', '직원들이 친절했습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user06', '편리한 교통이 장점입니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user07', '전반적으로 만족스러웠습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user08', '다시 방문하고 싶어요!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user09', '모든 것이 완벽했어요.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user10', '최고의 경험이었습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user11', '무난한 숙소였습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user12', '가격이 비싼 편입니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user13', '청결이 필요합니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user14', '서비스가 조금 부족했습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user15', '편안한 침대가 좋았습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user16', '특별한 경험은 아니었어요.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user17', '방음이 잘 되지 않았습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user18', '전반적으로 괜찮은 숙소입니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user19', '관리가 필요합니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user20', '기대 이상이었습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user21', '다음에 또 올게요.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user22', '가격이 너무 비쌌습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user23', '이용해볼만 합니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user24', '서비스가 좋았습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user25', '교통이 불편했습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user26', '직원들이 친절했습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user27', '조용한 숙소였습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user28', '시설이 오래되었습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user29', '방이 넓고 쾌적했습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user30', '뷰가 좋았습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user31', '친절한 직원들이 인상적이었습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user32', '특별히 마음에 드는 점이 없었습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user33', '관광지와 가까워 좋았습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user34', '추천하고 싶습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user35', '다시 방문할 의향이 있습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user36', '조식이 훌륭했습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user37', '비싼 가격에 비해 아쉬운 점이 많았습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user38', '가족과 함께하기 좋았습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user39', '전반적으로 괜찮았지만 개선이 필요합니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user40', '다시 방문하고 싶습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user41', '적당한 가격에 비해 괜찮은 숙소였습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user42', '전망이 뛰어나서 좋았습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user43', '무난한 숙소로 추천합니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user01', '친절한 서비스가 인상적이었습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user02', '체크인 절차가 매끄러웠습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user03', '방이 좁았습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'user04', '전반적으로 만족스러웠습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'agape', '비즈니스 출장에 적합한 곳입니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'test1', '재방문 의향이 있습니다.', 5);
