INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1013, 'pierrex2', '환상적인 경험이었습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1006, 'user05', '매우 편안한 숙박이었습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1007, 'user01', '평균적인 서비스였습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1008, 'user02', '위치가 아주 좋았습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1009, 'user03', '가격에 비해 아쉬웠습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1010, 'user04', '다시 방문하고 싶습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1011, 'user05', '깨끗하고 정돈된 곳이었습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1012, 'user06', '직원들이 매우 친절했습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1014, 'user07', '방이 좀 작았습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1015, 'user08', '아름다운 분위기였습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1018, 'user09', '밤에 소음이 있었습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1016, 'user10', '아침식사가 훌륭했습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1017, 'user11', '꼭 다시 오고 싶습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2001, 'user12', '방에서 경치가 좋았습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2002, 'user13', '서비스는 개선이 필요합니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2003, 'user14', '즐거운 경험이었습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2004, 'user15', '예상보다 아쉬웠습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2005, 'user16', '훌륭한 시설이었습니다!', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2006, 'user17', '직원들이 친절했습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2007, 'user18', '약간의 리노베이션이 필요합니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 2008, 'user19', '가성비가 좋았습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3001, 'user20', '다른 사람에게 추천합니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3002, 'user21', '평범한 숙박이었습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3003, 'user22', '훌륭한 고객 서비스였습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3004, 'user23', '그다지 깨끗하지 않았습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3005, 'user24', '전반적으로 환상적인 경험이었습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3006, 'user25', '즐거운 숙박이었습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3007, 'user26', '다시는 방문하지 않을 것입니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 3008, 'user27', '만족스러운 경험이었습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4001, 'user28', '위치가 정말 좋았습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4002, 'user29', '괜찮은 호텔이었습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4003, 'user30', '제 스타일은 아니었습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4004, 'user31', '훌륭한 직원들이었습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4005, 'user32', '짧은 숙박에는 괜찮았습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4006, 'user33', '즐거운 시간을 보냈습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4007, 'user34', '별로 감동적이지 않았습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 4008, 'user35', '비상식적인 서비스였습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 1005, 'user36', '다시는 묵지 않을 것입니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5005, 'user37', '편의 시설이 마음에 들었습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5006, 'user38', '너무 시끄러웠습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5007, 'user39', '가족 단위로 가기 좋은 곳이었습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5008, 'user40', '아주 즐거운 시간이었습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5009, 'user41', '추천하지 않습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5010, 'user42', '환상적인 경험이었습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5011, 'user43', '아주 깨끗했습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5012, 'user01', '그저 그랬습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 5013, 'user02', '평균적인 숙박이었습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6000, 'user03', '수영장이 마음에 들었습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6001, 'user04', '다시 올 것입니다!', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6002, 'user05', '괜찮은 경험이었습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6003, 'user06', '예상보다 좋지 않았습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6004, 'user07', '위치가 정말 좋았습니다!', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6005, 'user08', '매우 친절한 직원들이었습니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6006, 'user09', '괜찮았습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6007, 'user10', '더 나아질 수 있었습니다.', 2);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6008, 'user11', '가성비가 뛰어났습니다.', 5);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6009, 'user12', '만족스러운 숙박이었습니다.', 3);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6010, 'user13', '다시 올 것입니다.', 4);
INSERT INTO reviews (reviewID, hotelID, userID, content, star) VALUES (reviews_seq.nextval, 6006, 'user14', '끔찍한 경험이었습니다.', 1);
